class ApiConstant {
  static const String baseUrl = 'http://e-commerce.runasp.net/api/';
  static const String login  = 'Account/Login';
  static const String addRole  = 'Account/AddRole';
  static const String showUser  = 'Account/ShowUser';
  static const String register  = 'Account/Register';
  static const String forgetPassword  = 'Account/ForgetPassword';
  static const String changePassword  = 'Account/changePassword';
  static  const String getProductId='product/GetById';
  static  String getProductByName({ required String name})=>'product/GetByname?name=$name';
  static  String upDateProductId({ required int id})=>'product/$id';
  static  String deleteProductId({ required int id})=>'product/$id';
  static const String postProduct  = 'product';
  static const String getAllProduct  = 'product/GetAllProd';
  static const String GetAllProductbySortReview  = 'product/GetAllProductbySortReview';
  static const String getMyProduct  = 'product/MyProduct';
  static  String review({required int id})=>'Review?ProductId=$id';
  static const String getAllCategory  = 'Cactegory';
  static const String getAllShopProducts  = 'ShopProducts/GetAllShop';
  static  String addProductToCart({required int id})=> 'Cart/AddToCart/$id';
  static const String viewCart  = 'Cart/ViewCart';
  static  String removeProductFromCart({required int id}) => 'Cart/RemoveFromCart/$id';
  static const String postApplyShop='ApplyShop/ApplayShop';
  static const String totalPayment='Cart/TotalPayment';
  static const String checkOut='Order/CheckOut';
  static const String viewOrders='Order/ViewOrders';
  static const String getMyShop='ShopProducts/MyShop';
  static const String getAllApply='ApplyShop/GetAllApply';
  static const String createCactegory='Cactegory';
  static  String deleteApplyShop({ required int id})=>'ApplyShop/DeleteById?Id=$id';
static String createShop({required String imagePath})=>"ShopProducts?iamgefil=$imagePath";
static String updateShop({required String imagePath,required int id})=>"ShopProducts/Edit?id=$id&formFile=$imagePath";
  static  String deleteShop({ required int id})=>'ShopProducts/Delete?id=$id';
  static  String updateCategory({ required int id})=>'Cactegory?id=$id';
  static const String cancelOrder="Order/CancelOrder";
  static const String clientID="AWfArxCVw-fPdt1AtWeZEPsrtNMltTv-4kJJiwbDLxvdPQY7RKGMPHep0HjF9ghe3c-HIIUAKL5Dskgy";
  static const String paypalSecret="EBGajj8DJDiprbyb0dbyXqxPLR0XuMefmc7Ha7YR4H2OsWmDCjv18tz5OPU9cD3H-V_DftY0rz541wef";
  static const String paymentIntents="https://api.stripe.com/v1/payment_intents";
  static const String createCustomers="https://api.stripe.com/v1/customers";
  static const String contentType="application/x-www-form-urlencoded";
  static const String SecretKey="sk_test_51PZxtKRuX94qM5mKfveVnS9WeH7rd4mwrC3wGdFnuYW8jtkSBTyu08EIJl7WtCEkGaGWyh5CDcyZfxrynsmvgVq700O3NoHmuM";
  static const String stripePublishableKey="pk_test_51PZxtKRuX94qM5mKDqdoB09Rm40JzdshuwkIN0Z6dmV5S1wg0M1jl2FDjO1RR5yoIprJoft6W5rN6LdespfsGgkf00pGoJah7X";
}